state = {
    "current_temperature": 24.5,
    "setpoint": 30.0,
    "mode": "OFF",
    "trip_status": False,
    "heater_on": False,
    "pump_on": True,
    "relay_on": False,
    "buzzer_on": False,
    "led_heating": False,
    "led_holding": False,
    "led_fault": False,
    "led_ok": True,
    "failure_mode": "NONE",
}
